language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t jadczakd/overarchitected-fibonacci-fe-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jadczakd/overarchitected-fibonacci-fe-test npm run test

after_success:
  - docker build -t jadczakd/multi-client ./client
  - docker build -t jadczakd/multi-nginx ./nginx
  - docker build -t jadczakd/multi-server ./server
  - docker build -t jadczakd/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jadczakd/multi-client
  - docker push jadczakd/multi-nginx
  - docker push jadczakd/multi-server
  - docker push jadczakd/multi-worker